const projects = [
	"Simple Stopwatch",
	"Dynamic Color Changer",
	"Image Gallery with Modal",
	"Interactive Feedback Form",
	"Basic JavaScript Calculator",
	"To-Do List Application",
	"Random Quote Generator",
	"Animated Navigation Menu",
	"Countdown Timer",
	"Weather App",
	"Simple Chat Interface",
	"Text-to-Speech Converter",
	"Drawing Canvas",
	"Basic Game of Snake",
	"Online Survey Tool",
	"Personal Portfolio Website",
	"E-commerce Product Listing",
	"Blog with Comment Section",
	"Social Media Dashboard",
	"Music Player",
	"Video Player",
	"Code Editor",
	"Calendar App",
	"Task Management System",
	"Recipe Book",
	"Travel Planner",
	"Finance Tracker",
	"Fitness Tracker",
	"Learning Management System (LMS)",
	"Real-time Collaboration Tool",
	"Appointment Scheduler",
	"Document Editor",
	"Inventory Management System",
	"Restaurant Ordering System",
	"Hotel Booking System",
	"Movie Database",
	"Book Store",
	"Event Management Platform",
	"Online Forum",
	"Job Board",
	"Online Courses Platform",
	"Personalized News Aggregator",
	"AI Chatbot",
	"Augmented Reality App",
	"Virtual Reality Game",
	"Blockchain Explorer",
	"Decentralized Application (DApp)",
	"Cryptocurrency Tracker",
	"Machine Learning Model",
	"Data Visualization Dashboard",
	"Cloud Storage Solution",
	"Smart Home Automation",
	"Robotics Simulation",
	"Space Exploration App",
	"Genetic Analysis Tool",
	"Medical Diagnosis System",
	"Climate Change Model",
	"Urban Planning Simulator",
	"Disaster Relief Management",
	"Search Engine",
	"Email Client",
	"Social Network",
	"Online Gaming Platform",
	"Mobile App Development",
	"Web Development Framework",
	"Operating System",
	"Database Management System",
	"Artificial Intelligence Platform",
	"Internet of Things (IoT) Device",
	"Wearable Technology",
	"Biotechnology Research Tool",
	"Nanotechnology Simulation",
	"Quantum Computing Platform",
	"Sustainable Energy System",
	"Precision Agriculture Tool",
	"Smart Transportation System",
	"Educational Gaming Platform",
	"Assistive Technology for Disabilities",
	"Cybersecurity Defense System",
	"Space Colonization Planner",
	"Extraterrestrial Life Search",
	"Virtual World Simulator",
	"Brain-Computer Interface",
	"Mindfulness Meditation App",
	"Personal Growth Tracker",
	"Creative Writing Tool",
	"Music Composition Software",
	"Digital Art Editor",
	"Filmmaking Studio",
	"Photography Portfolio",
	"Gaming Development Kit",
	"Animation Studio",
	"Virtual Reality Storytelling",
	"Interactive Museum Exhibit",
	"Gamified Learning Experience",
	"Personalized Avatar Creator",
	"Online Fashion Designer",
	"Interior Design Planner",
	"Architectural Visualization Tool",
	"Landscape Design Software",
	"Urban Farm Management",
	"Wildlife Conservation Simulator",
	"Environmental Cleanup Tool",
	"Disaster Preparedness App",
	"Humanitarian Aid Logistics",
	"Global Poverty Reduction Initiative",
	"Education Reform Planner",
	"Healthcare Access Improvement",
	"Social Justice Advocacy Platform",
	"Peacekeeping Mission Simulation",
	"Diplomacy Training Program",
	"Cross-cultural Communication Tool",
	"Ethical Dilemma Simulator",
	"Global Governance Model",
	"Sustainable Development Planner",
	"Social Impact Measurement",
	"Impact Investing Platform",
	"Corporate Social Responsibility (CSR)",
	"Social Enterprise Incubator",
	"Nonprofit Management System",
	"Volunteer Matching Platform",
	"Citizen Engagement Tool",
	"Civic Innovation Lab",
	"Democratic Participation Platform",
	"Electoral Process Simulation",
	"Government Transparency Tool",
	"Policy Analysis Model",
	"Public Opinion Tracker",
	"Legislative Research System",
	"Judicial Process Simulator",
	"Law Enforcement Training Program",
	"Prison Rehabilitation System",
	"Criminal Justice Reform",
	"Human Rights Monitoring",
	"Civil Liberties Protection",
	"Conflict Resolution Mediator",
	"Peacebuilding Facilitator",
	"Reconciliation Process Simulator",
	"Restorative Justice Program",
	"Community Mediation Center",
	"Neighborhood Watch Initiative",
	"Public Safety Alert System",
	"Emergency Response Plan",
	"Disaster Recovery Coordinator",
	"Search and Rescue Simulator",
	"Fire Safety Education",
	"Water Resource Management",
	"Air Quality Monitoring",
	"Soil Conservation Planner",
	"Biodiversity Protection Initiative",
	"Endangered Species Recovery",
	"Wildlife Habitat Restoration",
	"Protected Area Management",
	"Sustainable Forestry Practices",
	"Renewable Energy Development",
	"Energy Efficiency Planner",
	"Climate Resilience Building",
	"Green Building Design",
	"Zero Waste Management",
	"Circular Economy Model",
	"Sustainable Consumption Education",
	"Ethical Supply Chain Management",
	"Fair Trade Practices",
	"Responsible Investing Guide",
	"Socially Responsible Banking",
	"Community Development Finance",
	"Microfinance Lending Program",
	"Small Business Support System",
	"Entrepreneurship Training Program",
	"Innovation Ecosystem Builder",
	"Technology Transfer Office",
	"Research and Development (R&D)",
	"Scientific Discovery Simulator",
	"Technological Advancement Model",
	"Knowledge Sharing Platform",
	"Open Source Software Initiative",
	"Collaborative Innovation Network",
	"Creative Commons Licensing",
	"Free Software Foundation",
	"Digital Rights Management (DRM)",
	"Copyright Law Reform",
	"Online Privacy Protection",
	"Data Security System",
	"Cybercrime Prevention Tool",
	"Ethical Hacking Simulator",
	"Vulnerability Assessment Scanner",
	"Penetration Testing Service",
	"Information Security Training",
	"Network Security Architecture",
	"Cloud Security Implementation",
	"Endpoint Security Solution",
	"Incident Response Management",
	"Business Continuity Plan",
	"Disaster Recovery Site",
	"Data Backup and Recovery",
	"System Redundancy Design",
	"High Availability Cluster",
	"Load Balancing System",
	"Performance Monitoring Tool",
	"Resource Optimization Planner",
	"Capacity Planning Model",
	"Infrastructure Automation System",
	"Continuous Integration and Continuous Delivery (CI/CD)",
	"DevOps Culture Transformation",
	"Agile Project Management",
	"Lean Software Development",
	"Kanban Board System",
	"Scrum Methodology Simulation",
	"Extreme Programming (XP)",
	"Test-Driven Development (TDD)",
	"Behavior-Driven Development (BDD)",
	"Pair Programming Practice",
	"Code Review Process",
	"Refactoring Techniques",
	"Software Architecture Design",
	"Design Patterns Implementation",
	"Data Structures and Algorithms",
	"Object-Oriented Programming (OOP)",
	"Functional Programming (FP)",
	"Aspect-Oriented Programming (AOP)",
	"Microservices Architecture",
	"Serverless Computing Platform",
	"Containerization Technology",
	"Orchestration Framework",
	"API Management System",
	"Event-Driven Architecture",
	"Message Queue Broker",
	"Distributed Transaction Manager",
	"Consistent Hashing Algorithm",
	"Fault Tolerance Design",
	"Scalability Optimization",
	"High Performance Computing (HPC)",
	"Big Data Analytics Platform",
	"Machine Learning as a Service (MLaaS)",
	"Artificial Intelligence as a Service (AIaaS)",
	"Robotic Process Automation (RPA)",
	"Cognitive Computing Platform",
	"Natural Language Processing (NLP)",
	"Computer Vision System",
	"Speech Recognition Technology",
	"Predictive Analytics Model",
	"Sentiment Analysis Tool",
	"Image Recognition Software",
	"Video Analysis Platform",
	"Audio Processing System",
	"Sensor Data Analysis",
	"Internet of Things (IoT) Analytics",
	"Cybersecurity Threat Intelligence",
	"Financial Fraud Detection",
	"Healthcare Predictive Modeling",
	"Personalized Marketing Campaign",
	"Customer Relationship Management (CRM)",
	"Supply Chain Optimization",
	"Logistics Route Planning",
	"Inventory Forecasting Model",
	"Demand Sensing Technology",
	"Dynamic Pricing Strategy",
	"Yield Management System",
	"Risk Management Framework",
	"Compliance Reporting Tool",
	"Regulatory Technology (RegTech)",
	"Legal Document Automation",
	"E-Discovery Software",
	"Intellectual Property Management",
	"Contract Lifecycle Management",
	"Governance, Risk, and Compliance (GRC)",
	"Digital Accessibility Audit",
	"Website Performance Optimization",
	"Mobile App Usability Testing",
	"User Interface (UI) Design",
	"User Experience (UX) Research",
	"Information Architecture (IA)",
	"Interaction Design (IxD)",
	"Visual Design (VD)",
	"Motion Design (MD)",
	"Accessibility Design (AD)",
	"Content Strategy (CS)",
	"Search Engine Optimization (SEO)",
	"Social Media Marketing (SMM)",
	"Email Marketing Automation",
	"Pay-Per-Click (PPC) Advertising",
	"Affiliate Marketing Program",
	"Content Marketing Campaign",
	"Inbound Marketing Strategy",
	"Outbound Sales Development",
	"Sales Automation Tool",
	"Lead Generation Platform",
	"Customer Acquisition Cost (CAC)",
	"Customer Lifetime Value (CLTV)",
	"Return on Investment (ROI)",
	"Key Performance Indicators (KPIs)",
	"Business Intelligence (BI)",
	"Competitive Analysis Tool",
	"Market Research Report",
	"Strategic Planning Model",
	"Organizational Development (OD)",
	"Leadership Training Program",
	"Team Building Exercise",
	"Employee Engagement Survey",
	"Performance Appraisal System",
	"Compensation and Benefits Plan",
	"Succession Planning Model",
	"Talent Management System",
	"Human Resources Management (HRM)",
	"Legal Compliance Auditing",
	"Financial Statement Analysis",
	"Budget Planning and Control",
	"Cash Flow Management",
	"Investment Portfolio Management",
	"Retirement Planning Simulator",
	"Estate Planning Advisor",
	"Tax Preparation Software",
	"Insurance Policy Comparison",
	"Debt Management Program",
	"Credit Score Improvement Guide",
	"Personal Finance Tracker",
	"Simple Color Palette Generator",
	"Typing Speed Tester",
	"Geolocation Tracker",
	"Interactive Map with Markers and Popups",
	"Dynamic Form Validator",
	"Progressive Image Loader",
	"Sortable and Filterable Table",
	"Markdown Editor with Preview",
	"Code Syntax Highlighter",
	"Custom Scrollbar Implementation",
	"Off-Canvas Navigation",
	"Interactive Data Visualization (Charts and Graphs)",
	"Real-time Typing Game",
	"Pomodoro Timer with Custom Settings",
	"Basic Drag and Drop Interface",
	"Audio Visualizer",
	"3D Perspective Carousel",
	"Animated Page Transitions",
	"Client-Side Search with Autocomplete",
	"Comment System with Nested Replies",
	"Simple Wiki Editor",
	"JSON Viewer/Editor",
	"Morse Code Translator",
	"Hex Color to RGB Converter",
	"QR Code Generator",
	"Password Strength Checker",
	"Dice Roller Simulator",
	"Rock Paper Scissors Game",
	"Simple Drawing App",
	"Bouncing Balls Animation",
	"Matrix Rain Effect",
	"Particle System Effect",
	"Scrolling Animation on Reveal",
	"Client Side CSV parser + Visual Table",
	"Animated Typewriter Effect",
	"Infinite Scroll Implementation",
	"Interactive Product Configurator",
	"Geolocation-Based Reminder App",
	"PWA (Progressive Web App) Weather Dashboard",
	"Web Speech API Voice Command Interface",
	"Interactive Piano Keyboard",
	"Simple Drum Machine",
	"Collaborative Whiteboard",
	"Drawing board that will generates to SVG or CSS code(creative element)",
	"Real-time Stock Ticker",
	"Dynamic Data Table with Sorting, Filtering, and Pagination (from JSON)",
	"Calendar with Drag-and-Drop Events",
	"Kanban Board Application with LocalStorage Persistence",
	"Recipe Search App with Ingredient Filtering",
	"Online Code Editor with Live Collaboration",
	"Markdown Previewer",
	"Data Visualization Dashboard (Charts and Graphs)",
	"Basic WebGL Game (3D Graphics)",
	"Real-time Chat Application",
	"Image Manipulation Editor",
	"Password Generator with Customizable Complexity",
	"Text Analyzer (Word Count, Frequency)",
	"Age Calculator based on Input + Dynamic changes in theme upon event, from day-color shift)",
	"Procedural Content Generator (text-based)",
	"Simulated Ecosystem with Interactive Elements",
	"Web Audio Synth with Visual Controls",
	"Personal Finance Dashboard",
	"Interactive Map with Custom Data Layers (Leaflet.js)",
	"Simple Code Compiler / Interpreter (JS-based Language)",
	"Game of Life Simulator with Custom Rules",
	"Text-Based Adventure Game with Dynamic Story",
	"AI-Powered Music Recommendation System",
	"Interactive Fiction Engine",
	"Collaborative Document Editor with Version Control",
	"Mind Mapping Application",
	"Interactive Periodic Table with Element Details",
	"Basic Spreadsheet with Formula Support",
	"CSS Grid Layout Generator",
	"RegExp Visualizer and Tester",
	"Simple Ray Tracer",
	"Cellular Automata Explorer",
	"L-System Generator",
	"Image Steganography Tool",
	"Brainfuck Interpreter",
	"Genetic Algorithm Visualizer",
	"Markov Chain Text Generator",
	"Wave Function Collapse Algorithm Demo",
	"Interactive Voronoi Diagram",
	"Interactive Audio Mixing Deck Controller",
	"CSS Specificity Visualizer",
	"Accessibility Contrast Checker (WCAG)",
	"Regex Tester with Syntax Highlighting and Explanation",
	"JSON Schema Validator with Interactive Editor",
	"Base64 Encoder/Decoder Tool",
	"HTML Minifier/Beautifier",
	"JavaScript Code Coverage Reporter",
	"Performance Monitoring Tool with Charts",
	"CSS Animation Timing Function Playground",
	"Web Font Optimizer (Subsetter)",
	"Responsive Image Generator (Different Sizes)",
	"Code Comparison Tool (Diff Viewer)",
	"HTTP Request Debugger (like Postman lite)",
	"URL Encoder/Decoder",
	"CORS Tester",
	"Website Technology Stack Detector (identifies framework)",
];

const projectTitle = document.getElementById("project");
const generate = document.querySelector("button");
function generatePro() {
    const name = projects[Math.floor(Math.random() * 416)];
    projectTitle.textContent = name;
}
generate.addEventListener("click", ()=> {
    generatePro();
});
